networks:
  autocomplete-network:
    driver: bridge

services:
  autocomplete_db:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - TZ=UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - postgres
      - -c
      - max_connections=1000
    env_file:
      - .env
    volumes:
      - postgres_autocomplete_data:/var/lib/postgresql/data
    networks:
      - autocomplete-network

  autocomplete_redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - autocomplete-network

volumes:
  postgres_autocomplete_data:
    driver: local