networks:
  autocomplete-network:
    driver: bridge

services:
  oauth_db:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - TZ=UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - postgres
      - -c
      - max_connections=1000
    env_file:
      - .env
    volumes:
      - postgres_oauth_data:/var/lib/postgresql/data
    networks:
      - autocomplete-network

volumes:
  postgres_oauth_data:
    driver: local